export const UNIVERSITY_LIST_REQUEST = "UNIVERSITY_LIST_REQUEST";
export const UNIVERSITY_LIST_SUCCESS = "UNIVERSITY_LIST_SUCCESS";
export const UNIVERSITY_LIST_FAIL = "UNIVERSITY_LIST_FAIL";
export const UNIVERSITY_LIST_RESET = "UNIVERSITY_LIST_RESET";

export const UNIVERSITY_SEARCH_REQUEST = "UNIVERSITY_SEARCH_REQUEST";
export const UNIVERSITY_SEARCH_SUCCESS = "UNIVERSITY_SEARCH_SUCCESS";
export const UNIVERSITY_SEARCH_FAIL = "UNIVERSITY_SEARCH_FAIL";

export const UNIVERSITY_FILTER_REQUEST = "UNIVERSITY_FILTER_REQUEST";
export const UNIVERSITY_FILTER_SUCCESS = "UNIVERSITY_FILTER_SUCCESS";
export const UNIVERSITY_FILTER_FAIL = "UNIVERSITY_FILTER_FAIL";