export const UNIVERSITY_LIST_REQUEST = "UNIVERSITY_LIST_REQUEST";
export const UNIVERSITY_LIST_SUCCESS = "UNIVERSITY_LIST_SUCCESS";
export const UNIVERSITY_LIST_FAIL = "UNIVERSITY_LIST_FAIL";
export const UNIVERSITY_LIST_RESET = "UNIVERSITY_LIST_RESET";

export const UNIVERSITY_SEARCH_REQUEST = "UNIVERSITY_SEARCH_REQUEST";
export const UNIVERSITY_SEARCH_SUCCESS = "UNIVERSITY_SEARCH_SUCCESS";
export const UNIVERSITY_SEARCH_FAIL = "UNIVERSITY_SEARCH_FAIL";

export const UNIVERSITY_FILTER_REQUEST = "UNIVERSITY_FILTER_REQUEST";
export const UNIVERSITY_FILTER_SUCCESS = "UNIVERSITY_FILTER_SUCCESS";
export const UNIVERSITY_FILTER_FAIL = "UNIVERSITY_FILTER_FAIL";

export const UNIVERSITY_CREATE_REQUEST = "UNIVERSITY_CREATE_REQUEST";
export const UNIVERSITY_CREATE_SUCCESS = "UNIVERSITY_CREATE_SUCCESS";
export const UNIVERSITY_CREATE_FAIL = "UNIVERSITY_CREATE_FAIL";
export const UNIVERSITY_CREATE_RESET = "UNIVERSITY_CREATE_RESET";

export const UNIVERSITY_DETAILS_REQUEST = "UNIVERSITY_DETAILS_REQUEST";
export const UNIVERSITY_DETAILS_SUCCESS = "UNIVERSITY_DETAILS_SUCCESS";
export const UNIVERSITY_DETAILS_FAIL = "UNIVERSITY_DETAILS_FAIL";

export const UNIVERSITY_UPDATE_REQUEST = "UNIVERSITY_UPDATE_REQUEST";
export const UNIVERSITY_UPDATE_SUCCESS = "UNIVERSITY_UPDATE_SUCCESS";
export const UNIVERSITY_UPDATE_FAIL = "UNIVERSITY_UPDATE_FAIL";
export const UNIVERSITY_UPDATE_RESET = "UNIVERSITY_UPDATE_RESET";

export const UNIVERSITY_DELETE_REQUEST = "UNIVERSITY_DELETE_REQUEST";
export const UNIVERSITY_DELETE_SUCCESS = "UNIVERSITY_DELETE_SUCCESS";
export const UNIVERSITY_DELETE_FAIL = "UNIVERSITY_DELETE_FAIL";
export const UNIVERSITY_DELETE_RESET = "UNIVERSITY_DELETE_RESET";